---
driver:
  name: vagrant
  customize:
    memory: 5120
    natdnshostresolver1: "on"
    natdnsproxy1: "on"

provisioner:
  name: chef_solo

platforms:
# - name: centos-6.5
# - name: ubuntu-12.04
  - name: ubuntu-14.04

suites:
  - name: default
    run_list:
      - recipe[kagent::install]
      - recipe[hadoop::install]
      - recipe[kagent::default]
      - recipe[hadoop::nn]
      - recipe[hadoop::rm]
      - recipe[hadoop::dn]
      - recipe[hadoop::nm]
      - recipe[hadoop::jhs]
      - recipe[hiway::install]
      - recipe[hiway::cuneiform]
#      - recipe[hiway::galaxy]
      - recipe[hiway::hadoop]
      - recipe[hiway::prepare_helloworld_cf]
      - recipe[hiway::run_helloworld_cf]
#      - recipe[hiway::prepare_montage_synthetic_dax]
#      - recipe[hiway::run_montage_synthetic_dax]
#      - recipe[hiway::prepare_galaxy101_ga]
#      - recipe[hiway::run_galaxy101_ga]
#      - recipe[hiway::prepare_wordcount_cf]
#      - recipe[hiway::prepare_variantcall_cf]
#      - recipe[hiway::prepare_montage_m17_4_dax]
#      - recipe[hiway::prepare_RNASeq_ga]

    attributes:
         hadoop:
            nn:
               private_ips: ["10.0.2.15"]
            dn:
               private_ips: ["10.0.2.15"]
            rm:
               private_ips: ["10.0.2.15"]
            nm:
               private_ips: ["10.0.2.15"]
            jhs:
               private_ips: ["10.0.2.15"]
            cluster: vagrant
         kmon:
            private_ips: ["10.0.2.15"]
            public_ips: ["10.0.2.15"]
         kagent:
            private_ips: ["10.0.2.15"]
            public_ips: ["10.0.2.15"]
         hiway:
            private_ips: ["10.0.2.15"]
            public_ips: ["10.0.2.15"]
         private_ips: ["10.0.2.15"]
         public_ips: ["10.0.2.15"]
         vagrant: "enabled"
