---
driver:
  name: vagrant
  customize:
    memory: 5120
    natdnshostresolver1: "on"
    natdnsproxy1: "on"

provisioner:
  name: chef_solo

platforms:
# - name: centos-6.5
# - name: ubuntu-12.04
  - name: ubuntu-14.04

suites:
  - name: default
    run_list:
      - recipe[kagent::install]
      - recipe[hadoop::install]
      - recipe[kagent::default]
      - recipe[hadoop::nn]
      - recipe[hadoop::rm]
      - recipe[hadoop::dn]
      - recipe[hadoop::nm]
      - recipe[hadoop::jhs]
      - recipe[hiway::install]
      - recipe[hiway::hadoop]
      - recipe[hiway::cuneiform]
      - recipe[hiway::cuneiform_helloworld_cf_prepare]
      - recipe[hiway::cuneiform_helloworld_cf_run]
      - recipe[hiway::cuneiform_variantcall_hg38_cf_prepare]
#      - recipe[hiway::galaxy]
      - recipe[hiway::hiway_wordcount_cf_prepare]
      - recipe[hiway::hiway_wordcount_cf_run]
      - recipe[hiway::hiway_montage_synthetic_dax_prepare]
      - recipe[hiway::hiway_montage_synthetic_dax_run]
#      - recipe[hiway::hiway_galaxy101_ga_prepare]
#      - recipe[hiway::hiway_galaxy101_ga_run]
#      - recipe[hiway::hiway_variantcall_cf_prepare]
#      - recipe[hiway::hiway_montage_m17_4_dax_prepare]
#      - recipe[hiway::hiway_RNASeq_ga_prepare]

    attributes:
         hadoop:
            nn:
               private_ips: ["10.0.2.15"]
            dn:
               private_ips: ["10.0.2.15"]
            rm:
               private_ips: ["10.0.2.15"]
            nm:
               private_ips: ["10.0.2.15"]
            jhs:
               private_ips: ["10.0.2.15"]
            cluster: vagrant
         kmon:
            private_ips: ["10.0.2.15"]
            public_ips: ["10.0.2.15"]
         kagent:
            private_ips: ["10.0.2.15"]
            public_ips: ["10.0.2.15"]
         hiway:
            private_ips: ["10.0.2.15"]
            public_ips: ["10.0.2.15"]
         private_ips: ["10.0.2.15"]
         public_ips: ["10.0.2.15"]
         vagrant: "enabled"
