---
driver:
  name: vagrant
  customize:
    memory: 4608
    cpus: 2
    natdnshostresolver1: "on"
    natdnsproxy1: "on"
  network:
  - ["forwarded_port", {guest: 8042, host: 8042}]
  - ["forwarded_port", {guest: 8080, host: 8080}]
  - ["forwarded_port", {guest: 8088, host: 8088}]
  - ["forwarded_port", {guest: 50070, host: 50070}]
  - ["forwarded_port", {guest: 50075, host: 50075}]

provisioner:
  name: chef_solo

platforms:
# - name: centos-6.5
# - name: ubuntu-12.04
  - name: ubuntu-14.04
  

suites:
  - name: default
    run_list:
      - recipe[kagent::install]
      - recipe[hadoop::install]
      - recipe[kagent::default]
      - recipe[hadoop::nn]
      - recipe[hadoop::rm]
      - recipe[hadoop::dn]
      - recipe[hadoop::nm]
      - recipe[hadoop::jhs]
      - recipe[hiway::install]
      - recipe[hiway::rm]
      - recipe[hiway::nm]
      - recipe[hiway::galaxy]
#      - recipe[hiway::cuneiform]
#      - recipe[hiway::helloworld_client]
#      - recipe[hiway::helloworld_run_loc]
#      - recipe[hiway::wordcount_client]
#      - recipe[hiway::wordcount_run_loc]
#      - recipe[hiway::variantcall_hg38_client]
#      - recipe[hiway::variantcall_hg38_worker]
#      - recipe[hiway::variantcall_hg38_run_hw]
#      - recipe[hiway::montage_synth_client]
#      - recipe[hiway::montage_synth_run_hw]
#      - recipe[hiway::galaxy101_client]
#      - recipe[hiway::galaxy101_worker]
#      - recipe[hiway::galaxy101_run_hw]
#      - recipe[hiway::variantcall_hg19_client]
#      - recipe[hiway::montage_m17_4_client]
#      - recipe[hiway::montage_m17_4_worker]
      - recipe[hiway::RNASeq_client]
      - recipe[hiway::RNASeq_worker]

    attributes:
         hadoop:
            nn:
               private_ips: ["10.0.2.15"]
            dn:
               private_ips: ["10.0.2.15"]
            rm:
               private_ips: ["10.0.2.15"]
            nm:
               private_ips: ["10.0.2.15"]
            jhs:
               private_ips: ["10.0.2.15"]
            cluster: vagrant
         kmon:
            private_ips: ["10.0.2.15"]
            public_ips: ["10.0.2.15"]
         kagent:
            private_ips: ["10.0.2.15"]
            public_ips: ["10.0.2.15"]
         hiway:
            private_ips: ["10.0.2.15"]
            public_ips: ["10.0.2.15"]
         private_ips: ["10.0.2.15"]
         public_ips: ["10.0.2.15"]
         vagrant: "enabled"
